import { NextResponse } from "next/server";
import { createSupabaseServiceClient } from "@/lib/supabase";
import { CreationFlowState } from "@/types";

interface FacilitatorPayload {
    facilitatorId: string;
    creatorName: string;
    organisation: string;
    sessionStartTime: number;
    sessionNotes: string;
    isPublic: boolean;
}

interface SaveRequest {
    state: CreationFlowState;
    artworkUrl: string; // Base64 data string
    creationStory: string; // The generated story
    facilitatorData?: FacilitatorPayload | null;
    marketplaceStatus: 'private' | 'pending_review' | 'printed';
}

export async function POST(request: Request) {
    try {
        const body: SaveRequest = await request.json();

        if (!body.artworkUrl || !body.state) {
            return NextResponse.json({ success: false, error: "Missing required fields" }, { status: 400 });
        }

        // Use service client to bypass RLS for server-side creation
        const supabase = await createSupabaseServiceClient();

        let validFd = body.facilitatorData;

        if (validFd?.facilitatorId) {
            const { data: checkFacil } = await supabase
                .from('facilitators')
                .select('id')
                .eq('id', validFd.facilitatorId)
                .single();
            if (!checkFacil) {
                console.warn(`Facilitator ID ${validFd.facilitatorId} not found. Stale session? Proceeding without facilitator.`);
                validFd = null;
            }
        }

        // 1. Create creator record (anonymous or named via facilitator or individual setup)
        const { data: creatorData, error: creatorError } = await supabase
            .from('creators')
            .insert({
                name: validFd?.creatorName || body.state.nickname || null,
                organisation: validFd ? validFd.organisation : '',
                language: 'en', // Defaulting to EN
                facilitator_id: validFd?.facilitatorId || null
            })
            .select('id')
            .single();

        if (creatorError || !creatorData) {
            console.error("Failed to create creator:", creatorError);
            return NextResponse.json({ success: false, error: `Database error during creator setup: ${creatorError?.message || 'Unknown'}` }, { status: 500 });
        }

        const creatorId = creatorData.id;

        // 2. Decode the Base64 image
        // Format: data:image/png;base64,iVBORw0KGgo...
        const matches = body.artworkUrl.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);

        if (!matches || matches.length !== 3) {
            return NextResponse.json({ success: false, error: "Invalid image format" }, { status: 400 });
        }

        const mimeType = matches[1];
        const base64Data = matches[2];
        const imageBuffer = Buffer.from(base64Data, 'base64');
        const arrayBuffer = new Uint8Array(imageBuffer).buffer;

        // Generate a unique filename for the storage bucket
        const fileExt = mimeType.split('/')[1] || 'png';
        const fileName = `${creatorId}_${Date.now()}.${fileExt}`;

        const { error: storageError } = await supabase.storage
            .from('artworks')
            .upload(fileName, arrayBuffer, {
                contentType: mimeType,
                upsert: false
            });

        if (storageError) {
            console.error("Storage upload failed:", storageError);
            return NextResponse.json({ success: false, error: `Failed to save image to CDN: ${storageError.message}` }, { status: 500 });
        }

        // 4. Retrieve the Public URL
        const { data: publicUrlData } = supabase.storage
            .from('artworks')
            .getPublicUrl(fileName);

        const cdnUrl = publicUrlData.publicUrl;

        // 5. Insert the artwork record into the database
        const { error: artworkError } = await supabase
            .from('artworks')
            .insert({
                creator_id: creatorId,
                image_url: cdnUrl,
                prompt_used: 'Generated by Gemini 2.5 Flash',
                creation_story: body.creationStory, // Store the generated story
                mood: body.state.mood || 'None',
                colour_palette: body.state.colour_palette || 'None',
                subject: body.state.subject || 'None',
                style: body.state.style || 'abstract_illustration',
                photo_used: !!body.state.photo_base64,
                moderation_pass: true,
                session_notes: validFd?.sessionNotes || null,
                is_public: validFd ? validFd.isPublic : false, // Still private internally until officially 'approved' for shop
                marketplace_status: body.marketplaceStatus || 'private',
                ip_owner: 'creator' // Strict requirement
            });

        if (artworkError) {
            console.error("Failed to save artwork record:", artworkError);
            return NextResponse.json({ success: false, error: "Database error saving artwork record" }, { status: 500 });
        }

        // 6. Record Session Data if Facilitator is active
        if (validFd) {
            const durationMinutes = Math.max(1, Math.round((Date.now() - validFd.sessionStartTime) / 60000));
            const { error: sessionError } = await supabase
                .from('sessions')
                .insert({
                    facilitator_id: validFd.facilitatorId,
                    creator_id: creatorId,
                    artworks_created: 1,
                    duration_minutes: durationMinutes,
                    notes: validFd.sessionNotes || null
                });

            if (sessionError) {
                console.error("Failed to construct session record, but artwork saved:", sessionError);
            }
        }

        return NextResponse.json({ success: true, data: cdnUrl });

    } catch (error) {
        console.error("Save API Error:", error);
        return NextResponse.json({
            success: false,
            error: "Internal server error during save."
        }, { status: 500 });
    }
}

